spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/adopte-un-rebelle
    driver-class-name: org.mariadb.jdbc.Driver
    username: stag
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
