spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/adopte-un-rebelle
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
